name: Origins-Monsters
version: 1.1.14
main: com.starshootercity.originsmonsters.OriginsMonsters
description: Origins-Reborn addon to add monster-themed origins
api-version: '1.19'
author: cometcake575

depend:
  - Origins-Reborn
